
<template>
	<div class="guiderisk">
	<div class="header">
	  <div class="header-left">
      <a href="#/"><img class="head-icon" src="../assets/svg/arrow-left.svg" /></a>
      </div>
    	<h1>风险告知</h1>
    </div>
    <div class="guiderisk-banner">
    <h2>规范期市秩序，坚持理性投资</h2>
    <span class="first">正视投资风险</span><span class="second">切勿过度投机</span><span class="third">保持合理仓位</span>
    </div>
    <div class="guide">
    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis felis vel lorem convallis venenatis nec eu elit. Integer posuere ut dolor non gravida. Maecenas maximus urna maximus libero egestas luctus. Etiam nec augue nec metus dictum consectetur non ac est. Proin nisl tortor, imperdiet vitae urna ut, condimentum euismod urna. Duis tincidunt massa ac tortor vehicula, vitae vestibulum nunc convallis. Etiam non finibus nisi, ac ultricies ante. Nulla mollis, felis ut suscipit iaculis, dui nibh suscipit mauris, quis consequat metus erat vitae eros. Etiam ut ante luctus lorem ullamcorper suscipit.</p>

		<p>Fusce mollis elit in sodales fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque eget vulputate velit. Praesent sit amet ex et dui cursus elementum. Cras scelerisque tincidunt mi maximus consequat. Morbi at elementum ante. Sed porttitor nibh ac interdum aliquam.</p>

		<p>Nam a fringilla turpis, quis congue diam. In a sapien iaculis, sodales nibh ultricies, laoreet urna. Sed convallis velit odio, et imperdiet ipsum imperdiet ut. Nunc blandit ex a erat blandit rutrum. Mauris in fringilla mauris. Mauris scelerisque augue nec elit tristique, id maximus leo vulputate. Nulla interdum mi non nibh elementum, a venenatis dui lacinia. Morbi et quam a dolor elementum tempus. Donec sit amet dolor eu nunc eleifend tristique. Morbi convallis tellus lobortis varius auctor. Sed risus mi, hendrerit at turpis vel, rhoncus vehicula tortor. Duis pellentesque eleifend sem, quis tempor nulla interdum in. Quisque rutrum auctor bibendum. Aliquam libero lectus, bibendum a turpis in, aliquet consectetur ante.</p>
    </div>
	</div>
</template>

<!-- Loads SCSS -->
<style lang="scss" scoped>
   @import "../assets/css/main.scss"
</style>
